---
- name: "Development / Tools / Deploy / Package / Provision application"
  vars:
    core_package:
      provision: true
    core_package_application: "{{ dev_tools_application }}"
    core_package_profiles: "{{ dev_tools_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.core.core_package"
...
