---
- name: "Development / Java / Deploy / Package / Provision application"
  vars:
    core_package:
      provision: true
    core_package_application: "{{ dev_java___deploy_profile['value'] }}"
    core_package_profiles: "{{
        dev_java_profiles[
          dev_java___deploy_profile['key']
        ]
      }}"
  ansible.builtin.include_role:
    name: "serdigital64.core.core_package"
...
