---
- name: "Development / OpenCL / Deploy / Package / Provision application"
  vars:
    core_package:
      provision: true
    core_package_application: "{{ dev_opencl_application }}"
    core_package_profiles: "{{ dev_opencl_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.core.core_package"
...
